const products = [
    {
        id: 1,
        name: "Diamond Cut Necklace",
        collection: "gold",
        type: "necklace",
        price: 1500,
        image: "images/products/gold/diamondcut.jpg",
        images: ["images/products/gold/diamondcut.jpg"],
        description: "Crafted to capture light from every angle, the Diamond Cut Necklace is designed for effortless elegance.",
        material: ["10K Yellow Gold"],
        lengths: ['18"'],
        finish: "Diamond Cut",
        width: "8 mm",
        weight: "Approx. 12.2 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 2,
        name: "Solid Gold Signature Piece",
        collection: "gold",
        type: "necklace",
        price: 1800,
        image: "images/products/gold/solidgoldnecklace.jpg",
        images: ["images/products/gold/solidgoldnecklace.jpg"],
        description: "A solid gold piece designed with quiet elegance and timeless presence.",
        material: ["10K Yellow Gold"],
        lengths: ['16"'],
        finish: "Polished",
        width: "3 mm",
        weight: "Approx. 13.9 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 3,
        name: "Solid Gold Earrings",
        collection: "gold",
        type: "earring",
        price: 350,
        image: "images/products/gold/goldearing.jpg",
        images: ["images/products/gold/goldearing.jpg"],
        description: "Solid gold earrings made for understated beauty and everyday refinement.",
        material: ["10K Yellow Gold"],
        lengths: ["One size"],
        finish: "Polished",
        weight: "Approx. 3 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 4,
        name: "Fancy Hoop Gold Earrings",
        collection: "gold",
        type: "earring",
        price: 300,
        image: "images/products/gold/gldearing1.jpg",
        images: ["images/products/gold/gldearing1.jpg"],
        description: "A refined pair of solid gold earrings designed to complete any signature look.",
        material: ["10K Yellow Gold"],
        lengths: ["One size"],
        finish: "Polished",
        weight: "Approx. 3 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 5,
        name: "Silver Necklace I",
        collection: "silver",
        type: "necklace",
        price: 115,
        image: "images/products/silver/silvernecklace.jpg",
        images: ["images/products/silver/silvernecklace.jpg"],
        description: "A clean silver necklace created for effortless everyday elegance.",
        material: ["925 Sterling Silver"],
        lengths: ['16"'],
        finish: "Polished",
        weight: "Approx. 10.3 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 6,
        name: "Silver Fancy Thin Chain",
        collection: "silver",
        type: "necklace",
        price: 175,
        image: "images/products/silver/silvernecklace.jpg",
        images: ["images/products/silver/silvernecklace.jpg"],
        description: "A timeless silver necklace with a soft shine and refined finish.",
        material: ["925 Sterling Silver"],
        lengths: ['16"'],
        finish: "Polished",
        weight: "Approx. 16 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 7,
        name: "Cubic Zirconia Silver Bracelet",
        collection: "silver",
        type: "bracelet",
        price: 200,
        image: "images/products/silver/silvbracelet.jpg",
        images: ["images/products/silver/silvbracelet.jpg"],
        description: "A delicate silver bracelet designed for graceful everyday wear.",
        material: ["925 Sterling Silver", "Cubic Zirconia"],
        lengths: ['7"'],
        finish: "Polished",
        weight: "Approx. 19.6 g",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 8,
        name: "Cubic Zirconia Butterfly Pendant",
        collection: "silver",
        type: "pendant",
        price: 230,
        image: "images/products/silver/butterflypendant.jpg",
        images: ["images/products/silver/butterflypendant.jpg"],
        description: "A cubic zirconia studded butterfly pendant created to catch light with delicate brilliance.",
        material: ["925 Sterling Silver", "Cubic Zirconia"],
        lengths: ["Pendant only"],
        finish: "High Polish",
        weight: "Details coming soon",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 9,
        name: "Cubic Zirconia Heart Set",
        collection: "silver",
        type: "set",
        price: 120,
        image: "images/products/silver/czpendant.jpg",
        images: ["images/products/silver/czpendant.jpg"],
        description: "A cubic zirconia studded heart pendant and earring set created to catch light with delicate brilliance.",
        material: ["925 Sterling Silver", "Cubic Zirconia"],
        lengths: ["Set"],
        finish: "High Polish",
        weight: "Details coming soon",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    },
    {
        id: 10,
        name: "Silver Hoop Earring",
        collection: "silver",
        type: "earring",
        price: 150,
        image: "images/products/silver/silverhoop.jpg",
        images: ["images/products/silver/silverhoop.jpg"],
        description: "A timeless silver hoop with a soft shine and refined finish.",
        material: ["925 Sterling Silver"],
        lengths: ["One size"],
        finish: "High Polish",
        weight: "Details coming soon",
        shipping: "Ships within 2–3 business days",
        packaging: "Presented in the A.Signature luxury gift box with polishing cloth and care guide."
    }
];